#!/usr/bin/env bash
# Phase 12 — ops：验收 + 部署轻量监控
# 用法：bash phase12-verify.sh
source "$(dirname "$0")/lib.sh"

log_step "Phase 12：验收 + 轻量监控"

# ── 1. 跑 remote_infra_matrix ───────────────────────────────────────────────
MATRIX_SCRIPT="${SETU_SRC}/docs/testnet/testnet-infra/scripts/remote_infra_matrix.sh"
if [ -x "$MATRIX_SCRIPT" ]; then
    log_info "[1/2] 运行 remote_infra_matrix..."
    cd "$SETU_SRC"
    bash "$MATRIX_SCRIPT" || {
        log_err "remote_infra_matrix 失败，请检查日志"
        exit 1
    }
    log_ok "remote_infra_matrix 全部 PASS"
else
    log_warn "未找到 ${MATRIX_SCRIPT}，跳过自动验收"
fi

# ── 2. 部署 health_probe.sh + cron ─────────────────────────────────────────
log_info "[2/2] 安装 health_probe.sh + cron..."

DEPLOY_DIR=/opt/setu-deploy/scripts
CONF_DIR=/etc/setu-deploy
sudo install -d -o "$USER" -g "$USER" "$DEPLOY_DIR"
sudo install -d -m 755 "$CONF_DIR"
install -m 755 "$(dirname "$(readlink -f "$0")")/health_probe.sh" "$DEPLOY_DIR/health_probe.sh"

# 从 inventory.env 渲染 hosts.env（避免 health_probe 硬编码漂移）
_hosts_line=""
for h in "${VAL_ALIASES[@]}"; do
    _ip=$(resolve_host "$h")
    _hosts_line+="${h}:${_ip} "
done

# Gateway 探测 URL：有域名走 https，否则走 http://gw_ip
_gw_ip=$(resolve_host "${GATEWAY_ALIAS:-ops}")
if [ -n "${GATEWAY_DOMAIN:-}" ] && [[ "${GATEWAY_DOMAIN}" != REPLACE-* ]]; then
    _gw_url="https://${GATEWAY_DOMAIN}/api/v1/health"
else
    _gw_url="http://${_gw_ip}/api/v1/health"
fi

sudo tee "$CONF_DIR/hosts.env" >/dev/null <<EOF
# Auto-generated by phase12-verify.sh from inventory.env
SETU_HEALTH_HOSTS="${_hosts_line% }"
HTTP_PORT=${HTTP_PORT}
SETU_HEALTH_LOG=/var/log/setu-health.log
GATEWAY_HEALTH_URL="${_gw_url}"
GATEWAY_DOMAIN="${GATEWAY_DOMAIN:-}"
CERT_WARN_DAYS=14
EOF
log_ok "已写 $CONF_DIR/hosts.env"

sudo touch /var/log/setu-health.log
sudo chown "$USER" /var/log/setu-health.log

# 装到当前用户 crontab（去重 + 静默输出）
CRON_LINE="* * * * * $DEPLOY_DIR/health_probe.sh >/dev/null 2>&1"
( crontab -l 2>/dev/null | grep -v "health_probe.sh" ; echo "$CRON_LINE" ) | crontab -

log_ok "health_probe.sh 已部署，cron 每分钟执行"
log_info "查看日志：tail -f /var/log/setu-health.log"

# ── 3. BUG-010 闭环 tracing 计数器（V1 ACCEPT 硬性要求）─────────────────────
# 来源：docs/release-doc/test-v1-inner/03-known-internal-bugs.md
# 这 7 个 tracing target 在 V1 ACCEPT 时全部为 0；任一非 0 即认为 BUG-010 家族复发。
log_info "[3/3] BUG-010 闭环 tracing 计数器（近 10 分钟须全为 0）..."
BUG010_TARGETS=(
    "anchor_chain_root_mismatch"
    "CF dropped on apply failure"
    "pending_builds_count >= 2"
    "leader_root_self_mismatch"
    "leader_base_drift"
    "follower_post_apply_root_drift"
    "apply_state_change_out_of_band"
)
BUG010_FAIL=0
for HOST in "${VAL_ALIASES[@]}"; do
    for tgt in "${BUG010_TARGETS[@]}"; do
        cnt=$(mssh "$HOST" "sudo journalctl -u setu-validator --since '10 min ago' --no-pager 2>/dev/null | grep -c -- $(printf '%q' "$tgt")" 2>/dev/null || echo 0)
        cnt=${cnt:-0}
        if [ "$cnt" -gt 0 ]; then
            log_err "[$HOST] 检出 BUG-010 信号 '${tgt}' x${cnt}（必须为 0）"
            BUG010_FAIL=1
        fi
    done
done
if [ "$BUG010_FAIL" -ne 0 ]; then
    log_err "BUG-010 tracing 计数器非 0：详见 docs/release-doc/test-v1-inner/03-known-internal-bugs.md"
    log_err "立即冻结现场：ssh root@<host> 'cp -r /opt/setu/data /opt/setu/data.frozen-\$(date +%s)'"
    exit 1
fi
log_ok "BUG-010 闭环 tracing：3 节点 × 7 信号 = 0"

# ── 4. 手工验收提示 ─────────────────────────────────────────────────────────
log_warn "手工验收清单（建议）："
echo "  1. 关掉任意 1 台 validator，集群仍出块（BFT 容错）"
echo "     sudo systemctl stop setu-validator setu-solver   # 在 val-1"
echo "     for h in val-2 val-3; do curl -sf http://\$(resolve)/api/v1/health | jq .dag_events_count; done"
echo "  2. 重启后追上 DAG"
echo "  3. tail -f /var/log/setu-health.log 看监控有数据"

log_ok "Phase 12 完成"
